### PR TITLE
Disable django nose logs bellow critical

### PR DESCRIPTION
**Pull request by JohnMwashuma**

### CODE REVIEW

**Review by KipSigei — APPROVED** [review]

**Comment by JohnMwashuma** [comment]
@pld I think we can remove our project from travis

**Comment by pld** [comment]
agree, do you know how to do that?

**Comment by JohnMwashuma** [comment]
> agree, do you know how to do that?

There should be that option [here](https://app.travis-ci.com/github/onaio/tally-ho/settings), I can't find it cause of my permissions.

**Comment by pld** [comment]
cool done, I think

**Pull request merged**
